const CANVAS = document.querySelector('canvas');
const CANVAS_CONTEXT = CANVAS.getContext('2d');
const SPRITES = new Image()
SPRITES.src = './sprites.png'

const GRAVITY = 0.25

const GROUND = {
  SPRITE_POSITION_X: 0,
  SPRITE_POSITION_Y: 610,
  WIDTH: 224,
  HEIGHT:112,
  CANVAS_POSITION_X:0,
  CANVAS_POSITION_Y:CANVAS.height-112,
  desenha() {
    CANVAS_CONTEXT.drawImage(
      SPRITES,
      GROUND.SPRITE_POSITION_X,GROUND.SPRITE_POSITION_Y,
      GROUND.WIDTH,GROUND.HEIGHT,
      GROUND.CANVAS_POSITION_X,GROUND.CANVAS_POSITION_Y,
      GROUND.WIDTH,GROUND.HEIGHT,
    )

    CANVAS_CONTEXT.drawImage(
      SPRITES,
      GROUND.SPRITE_POSITION_X,GROUND.SPRITE_POSITION_Y,
      GROUND.WIDTH,GROUND.HEIGHT,
      GROUND.CANVAS_POSITION_X + GROUND.WIDTH ,GROUND.CANVAS_POSITION_Y,
      GROUND.WIDTH,GROUND.HEIGHT,
    )
  }
}

const BACKGROUND = {
  SPRITE_POSITION_X: 390,
  SPRITE_POSITION_Y: 0,
  WIDTH: 275,
  HEIGHT:204,
  CANVAS_POSITION_X:0,
  CANVAS_POSITION_Y:CANVAS.height-204,
  desenha() {
    CANVAS_CONTEXT.fillStyle= '#70C5CE';
    CANVAS_CONTEXT.fillRect(0,0,CANVAS.height, CANVAS.width);
    CANVAS_CONTEXT.drawImage(
      SPRITES,
      BACKGROUND.SPRITE_POSITION_X,BACKGROUND.SPRITE_POSITION_Y,
      BACKGROUND.WIDTH,BACKGROUND.HEIGHT,
      BACKGROUND.CANVAS_POSITION_X,BACKGROUND.CANVAS_POSITION_Y,
      BACKGROUND.WIDTH,BACKGROUND.HEIGHT,
    )
    CANVAS_CONTEXT.drawImage(
      SPRITES,
      BACKGROUND.SPRITE_POSITION_X,BACKGROUND.SPRITE_POSITION_Y,
      BACKGROUND.WIDTH,BACKGROUND.HEIGHT,
      BACKGROUND.CANVAS_POSITION_X + BACKGROUND.WIDTH,BACKGROUND.CANVAS_POSITION_Y,
      BACKGROUND.WIDTH,BACKGROUND.HEIGHT,
    )
  }
}

const PLAYER = {
  SPRITE_POSITION_X: 0,
  SPRITE_POSITION_Y: 0,
  WIDTH: 33,
  HEIGHT:24,
  CANVAS_POSITION_X:10,
  CANVAS_POSITION_Y:CANVAS.height / 2 - GROUND.HEIGHT,
  SPEED: 0,

  atualiza() {
    PLAYER.SPEED = PLAYER.SPEED + GRAVITY;
    PLAYER.CANVAS_POSITION_Y = PLAYER.CANVAS_POSITION_Y + PLAYER.SPEED;
  },
  desenha() {
    CANVAS_CONTEXT.drawImage(
      SPRITES,
      PLAYER.SPRITE_POSITION_X,PLAYER.SPRITE_POSITION_Y,
      PLAYER.WIDTH,PLAYER.HEIGHT,
      PLAYER.CANVAS_POSITION_X,PLAYER.CANVAS_POSITION_Y,
      PLAYER.WIDTH,PLAYER.HEIGHT,
    )
  }
}


function loop(){
  PLAYER.atualiza()
  BACKGROUND.desenha();
  GROUND.desenha();
  PLAYER.desenha();
  requestAnimationFrame(loop);
}

loop();
